/**
 * Qmd — Command handler for /qmd.
 *
 * Generates a Q.md file in the project root that defines project-specific
 * conventions, rules, and guidelines. The file is generated by analyzing
 * the project's codebase via the LLM, and the user can edit it afterwards.
 *
 * Usage: /qmd ["<instructions>"]
 *
 * Optional instructions can be provided in quotes to guide the generator,
 * e.g. `/qmd "The descriptions should never have icons in them"`.
 *
 * The generated Q.md file will be automatically picked up by the agent
 * on subsequent sessions (via applyAgentProfile's loadProjectRules).
 */

import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import chalk from "chalk";
import type { Agent } from "@q/agent-core";
import type { SlashCommandHost } from "./types.js";

/**
 * Handle /qmd — generate a Q.md file with project conventions.
 *
 * Accepts optional user instructions in quotes, e.g.:
 *   /qmd "The descriptions should never have icons in them"
 *   /qmd "Use tabs for indentation, max line length 100"
 */
export async function handleQmdCommand(
  host: SlashCommandHost,
  args: string,
): Promise<void> {
  host.track("command", { command: "qmd" });

  const workDir = host.appState.workDir;
  const qmdPath = resolve(workDir, "Q.md");

  // Check if Q.md already exists
  if (existsSync(qmdPath)) {
    host.showNotice(
      "Q.md already exists",
      "The file Q.md already exists in your project root. Edit it manually to update your project rules, or delete it first to regenerate.",
    );
    host.showStatus("ℹ️  Q.md already exists at: " + qmdPath, "info");
    return;
  }

  // Parse optional user instructions (strip surrounding quotes if present)
  const userInstructions = parseUserInstructions(args);

  host.showStatus("🔍 Analyzing project to generate conventions...", "info");

  try {
    // Build a prompt for the LLM to analyze the project
    const prompt = buildQmdPrompt(workDir, userInstructions);

    // Use the agent's LLM to generate the Q.md content
    if (!host.agent.runGeneration) {
      host.showError("No active agent/LLM available. Please configure a provider first.");
      return;
    }

    const systemReminder = buildSystemReminder(userInstructions);

    const result = await host.agent.runGeneration(prompt, systemReminder);

    if (!result || !result.trim()) {
      host.showError("Failed to generate Q.md content. The LLM returned an empty response.");
      return;
    }

    // Write the Q.md file
    writeFileSync(qmdPath, result.trim() + "\n", "utf-8");

    host.showNotice(
      "Q.md generated!",
      `Project conventions written to ${qmdPath}. You can edit this file anytime to update your project rules. The agent will automatically load these rules on every request.`,
    );
    host.showStatus(`✅ Q.md created at: ${qmdPath}`, "success");
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    host.showError(`Failed to generate Q.md: ${msg}`);
  }
}

/**
 * Handle /qmd in non-TUI interactive mode (readline-based).
 * Exported for use by main.ts.
 */
export async function handleQmdInteractive(
  agent: Agent,
  workDir: string,
  userInstructions?: string,
): Promise<void> {
  const qmdPath = resolve(workDir, "Q.md");

  if (existsSync(qmdPath)) {
    console.log(chalk.yellow("⚠ Q.md already exists at: " + qmdPath));
    console.log(chalk.dim("  Edit it manually to update your project rules, or delete it first to regenerate."));
    return;
  }

  console.log(chalk.cyan("🔍 Analyzing project to generate conventions..."));

  try {
    const prompt = buildQmdPrompt(workDir, userInstructions);
    const systemReminder = buildSystemReminder(userInstructions);

    agent.context.appendSystemReminder(systemReminder, { kind: "system_trigger", name: "qmd-generation" });
    const turnId = agent.turn.prompt(prompt);
    if (turnId === null) {
      console.log(chalk.red("✗ Could not launch turn (another turn is active)."));
      return;
    }
    await agent.turn.waitForCurrentTurn();

    const messages = agent.context.messages;
    const assistantMessages = messages.filter((m: any) => m.role === "assistant");
    const lastAssistant = assistantMessages[assistantMessages.length - 1];
    const result = lastAssistant?.content ?? "";

    if (!result || !result.trim()) {
      console.log(chalk.red("✗ Failed to generate Q.md content. The LLM returned an empty response."));
      return;
    }

    writeFileSync(qmdPath, result.trim() + "\n", "utf-8");
    console.log(chalk.green(`✅ Q.md created at: ${qmdPath}`));
    console.log(chalk.dim("  You can edit this file anytime to update your project rules."));
    console.log(chalk.dim("  The agent will automatically load these rules on every request."));
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.log(chalk.red(`✗ Failed to generate Q.md: ${msg}`));
  }
}

// ── Helpers ────────────────────────────────────────────────────────────

/**
 * Parse optional user instructions from the command arguments.
 * Strips surrounding quotes (single or double) if present.
 */
function parseUserInstructions(args: string): string | undefined {
  const trimmed = args.trim();
  if (!trimmed) return undefined;

  // Strip surrounding quotes
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1).trim();
  }

  return trimmed;
}

/**
 * Build the system reminder for the LLM generation turn.
 * Includes user instructions if provided.
 */
function buildSystemReminder(userInstructions?: string): string {
  let reminder = `You are generating a Q.md file for a project. 
Your task is to analyze the project structure and produce a Q.md file with conventions, rules, and guidelines.
Output ONLY the content of the Q.md file. No explanations, no commentary.
The output will be written directly to Q.md. Use markdown formatting.`;

  if (userInstructions) {
    reminder += `\n\nThe user has provided the following additional instructions that MUST be incorporated into the Q.md file:\n${userInstructions}`;
  }

  return reminder;
}

/**
 * Build a prompt that asks the LLM to analyze the project and produce
 * a Q.md file with conventions, rules, and guidelines.
 */
function buildQmdPrompt(workDir: string, userInstructions?: string): string {
  let prompt = `You are analyzing a software project at "${workDir}" to produce a Q.md file.

Q.md is a project-level configuration file that defines conventions, rules, and guidelines
for AI coding agents working on this project. The file is loaded automatically at the
start of every session and embedded into the agent's system prompt.

Your task is to analyze the project structure, code patterns, and conventions, then
produce a comprehensive Q.md file. Follow these steps:

1. First, explore the project structure using Glob to understand the codebase layout.
2. Read key configuration files (package.json, tsconfig.json, README.md, etc.) to
   understand the tech stack and project conventions.
3. Read representative source files to understand coding style, naming conventions,
   import patterns, and documentation style.
4. Synthesize your findings into a well-structured Q.md file.

The Q.md file should include sections like:

- **Project Overview**: Brief description of what the project does
- **Tech Stack**: Languages, frameworks, tools used
- **Code Conventions**: Naming conventions, file organization, import style, etc.
- **Architecture Guidelines**: How the codebase is structured, key patterns
- **Testing Conventions**: Testing framework, naming, structure
- **Documentation Standards**: How code should be documented
- **Workflow Rules**: Any specific processes or rules for the agent to follow
- **Common Patterns**: Recurring patterns the agent should be aware of`;

  if (userInstructions) {
    prompt += `\n\nThe user has provided the following additional requirements that MUST be reflected in the Q.md file:\n${userInstructions}\n\nMake sure these requirements are woven into the appropriate sections above.`;
  }

  prompt += `\n\nIMPORTANT: Output ONLY the content of the Q.md file. No explanations, no commentary.
The output will be written directly to Q.md. Use markdown formatting.

Start by exploring the project structure.`;

  return prompt;
}
