/**
 * Config Writer — writes the onboarding choices to disk and creates
 * environment variable exports.
 *
 * Creates $HOME/.Q/config.toml and $HOME/.Q/env (a shell script with
 * Q_PROVIDER, Q_MODEL, Q_API_KEY exports).
 * Also writes the $HOME/.Q/.onboarding-complete semaphore.
 */

import { mkdirSync, writeFileSync, existsSync, unlinkSync } from "node:fs";
import { resolve } from "node:path";
import { homedir } from "node:os";
import type { OnboardingState } from "./types.js";

/**
 * Write the onboarding config to disk and generate the env file.
 */
export function writeOnboardingConfig(state: OnboardingState): void {
  const home = homedir();
  const qDir = resolve(home, ".Q");
  mkdirSync(qDir, { recursive: true });

  const provider = state.provider?.type ?? "";
  const model = state.model ?? "";
  const apiKey = state.credentials?.apiKey ?? "";

  // ── TOML config ──
  const configLines: string[] = [];
  configLines.push("# Q Configuration — generated by onboarding wizard");
  configLines.push(`# Provider: ${state.provider?.name ?? provider}`);
  configLines.push(`# Model: ${model}`);
  configLines.push("");

  configLines.push(`provider = "${provider}"`);
  configLines.push(`model = "${model}"`);
  configLines.push(`apiKey = "${apiKey.replace(/"/g, '\\"')}"`);

  if (provider === "ollama") {
    configLines.push(`# Ollama: no API key needed — model name is sufficient`);
  }

  configLines.push("");

  // Models section
  configLines.push("[models.default]");
  configLines.push(`provider = "${state.provider?.name ?? provider}"`);
  configLines.push(`name = "${model}"`);
  configLines.push(`maxContextSize = 128000`);
  configLines.push(`maxOutputSize = 8192`);

  configLines.push("");

  // Display
  configLines.push("[display]");
  configLines.push(`animations = true`);
  configLines.push(`linkPreview = true`);
  configLines.push(`imagePreview = true`);

  configLines.push("");

  // Permission
  configLines.push(`defaultPermissionMode = "ask"`);

  const toml = configLines.join("\n");
  writeFileSync(resolve(qDir, "config.toml"), toml, { mode: 0o600 });

  // ── Shell env file ──
  const envLines: string[] = [];
  envLines.push("#!/bin/sh");
  envLines.push("# Q environment variables — generated by onboarding wizard");
  envLines.push(`export Q_PROVIDER="${provider}"`);
  envLines.push(`export Q_MODEL="${model}"`);
  if (apiKey && provider !== "ollama") {
    envLines.push(`export Q_API_KEY="${apiKey}"`);
  }
  writeFileSync(resolve(qDir, "env"), envLines.join("\n"), { mode: 0o600 });

  // ── Semaphore ──
  writeFileSync(resolve(qDir, ".onboarding-complete"), "", { mode: 0o644 });
}

/**
 * Delete the onboarding semaphore — used by the --setup flag to force re-run.
 */
export function clearOnboardingComplete(): void {
  const semaphore = resolve(homedir(), ".Q", ".onboarding-complete");
  try {
    if (existsSync(semaphore)) {
      unlinkSync(semaphore);
    }
  } catch {
    // ignore
  }
}